[project]
name = "harvest-iq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.1",
    "django-celery-results>=2.6.0",
    "django-redis>=7.0.0",
    "djangorestframework>=3.18.0",
    "ipykernel>=7.3.0",
    "langgraph>=1.2.11",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
    "psycopg[pool]>=3.3.4",
    "python-dotenv>=1.2.2",
    "scikit-learn>=1.9.0",
    "xgboost>=3.4.0",
]
